language: node_js
before_deploy:
- npm install -g hexo
- npm install
- hexo generate
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
  local_dir: public
  repo: Icear/Icear.github.io
  target_branch: master
env:
  global:
    secure: FjtpHblSuY6JJSuPParvAjr967wvvgxleolIpPEzdzdmstsd+i3dj6hiwXUSHtS+1SeZaghl65DCsHjPph5KTk6vWNeekcf8UvVvLeelpw5HXCeiuVBo5fT3pdUYNzcajMKj9jRCLSutDBKV0sy5TwR8w+eslneASQpC3r/2ksfwz6R1zZCFL3pm0ZTYIC5E635um5qzjhWNJsNV+B+5M8AZqOlFFLquz35CzASvYpMd63OQ6ZMh5EOmEHcNAr1WUKMCl3cEa3DRodgksSWBRVUZpSBVu1e1vfhrXcu90Z6d8Xx/FC78Yh9zHb2gWTGb2426JjYf9yNmA3Mt0XGDFuvEaVWTBTic0Ml8MSU5ifSsuBoTxHUGbfvS5FJBGM65vBTXMuTkWCnKkuKFo2EHZ0UihXpljgm1ZXjosaAS6bwvr8ehUIXMz5aHOYDxuDEUERotG5iyPMvtKOixtyY8L71cRsp7O+0s+WzyuAEp2NFQphyEXbNjhwRir/XR1HBxpZkdm1SENuxL82hMx5vsvdGMO/DId/nkYf7omxz8LVjGizFfUFjIa841g/Naj6DJ8bWFGnNHgRpJwAJ0kFCTua6rV7FrzbSex2GhbqTPJKL629XyM46rhGxnYKywdQmqNnyI5qqkGqc2YbyZIUChNC6X3rT0Ox+YRLCyw/tbJsE=
