name: Hexo Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v1
    - name: update submodule
      run: |
        git submodule update --init
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: prepare node package
      run: |
        npm ci
      env:
        CI: true
    - name: Setup git environment
      env:
        ACTION_DEPLOY_KEY: ${{secrets.ACTION_DEPLOY_KEY}}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name "icear"
        git config --global user.email "Icear@users.noreply.github.com"
    - name: generate 
      run: |
        npx hexo version
        npm run clean
        npm run build
    - name: publish
      run: |
        npm run deploy
